### ISSUE TITLE
Overview GUI

### ISSUE THREAD

**Issue by dhsavell** [dhsavell/ajo#2]
This issue tracks the progress of the Ajo's Overview activity. This screen lists all journals a user has created and highlights upcoming events and to-dos.

**Overview**
- [ ] Listing of all saved journals
- [ ] Ability to open individual journals
- [ ] Prioritization of frequent journals
  - [ ] Ability to disable automatic sorting in favor of manual organization
- [ ] Various tasks and info
  - [ ] Ability to immediately start new entry in the last used journal
  - [ ] Listing of current and upcoming events (or any statements with associated dates)
    - [ ] Quick actions (i.e. reschedule, contact associated contacts) for events
